function node = yaml_alias_node(anchor)

if ~(ischar(anchor) && size(anchor,1) <= 1) || iscellstr(anchor)
    error('yaml_alias_node:badAnchor', 'anchor must be a string');
end

node = struct( 'type', int32(4), ...
    'value', [], ...
    'tag', '', ...
    'anchor', anchor, ...
    'implicit', int32(0), ...
    'style', int32(0) );